[package]
name = "SLL"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = { version = "0.5.1", features = ["auto-color"] }
num-traits = "0.2.19"
parking_lot = "0.12.3"
pest = "2.8.0"
pest_derive = "2.8.0"
